export const panelStyles = {
  header: {
    display: "grid",
    gap: "8px",
    paddingBottom: "14px",
    borderBottom: "1px solid var(--color-border)",
  },
  section: {
    display: "grid",
    gap: "2px",
    marginTop: "8px",
  },
  sectionTitle: {
    margin: "0 0 8px 0",
    color: "#90a1b9",
    fontSize: "11px",
    fontWeight: "bold",
    textTransform: "uppercase" as const,
    letterSpacing: "0.55px",
    paddingLeft: "6px",
  },
  tree: {
    display: "grid",
    gap: "2px",
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  rootNode: {
    display: "grid",
    gap: "2px",
  },
  rootLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#314158",
    fontSize: "13px",
    fontWeight: 500,
    padding: "6px 8px",
    borderRadius: "4px",
  },
  nodeButton: {
    width: "100%",
    border: 0,
    borderRadius: "4px",
    background: "transparent",
    color: "#45556c",
    cursor: "pointer",
    font: "inherit",
    padding: "6px",
    textAlign: "left" as const,
    display: "flex",
    alignItems: "center",
    gap: "8px",
    overflow: "hidden",
  },
  nodeStatic: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px",
    color: "#314158",
    fontSize: "13px",
    fontWeight: 500,
    borderRadius: "4px",
  },
  nodeContent: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flex: 1,
    minWidth: 0,
  },
  nodeLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
    flex: 1,
    fontSize: "13px",
    fontWeight: 400,
  },
  nodeTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  nodeMeta: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "6px",
    color: "var(--color-text-muted)",
    fontSize: "12px",
    lineHeight: 1.35,
  },
  children: {
    display: "grid",
    gap: "2px",
    margin: "2px 0 0 10px",
    padding: 0,
    listStyle: "none",
  },
  project: {
    display: "grid",
    gap: "2px",
  },
} as const;
