export const panelStyles = {
  header: {
    display: "grid",
    gap: "8px",
    paddingBottom: "14px",
    borderBottom: "1px solid var(--color-border)",
  },
  metaRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    alignItems: "center",
  },
  badge: {
    border: "1px solid var(--color-border)",
    borderRadius: "999px",
    padding: "2px 8px",
    color: "var(--color-text-secondary)",
    fontSize: "12px",
    fontWeight: 650,
    lineHeight: 1.5,
  },
  createForm: {
    display: "grid",
    gap: "8px",
    marginTop: "14px",
    paddingTop: "14px",
    borderTop: "1px solid var(--color-border)",
  },
  createRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "8px",
  },
  createInput: {
    boxSizing: "border-box" as const,
    minWidth: 0,
    width: "100%",
    border: "1px solid var(--color-border)",
    borderRadius: "4px",
    padding: "6px 8px",
    color: "var(--color-text-primary)",
    background: "var(--color-surface)",
    font: "inherit",
  },
  createButton: {
    border: "1px solid var(--color-accent)",
    borderRadius: "4px",
    padding: "6px 10px",
    color: "#ffffff",
    background: "var(--color-accent)",
    fontWeight: 650,
  },
  section: {
    display: "grid",
    gap: "8px",
    marginTop: "16px",
  },
  sectionTitle: {
    margin: 0,
    color: "var(--color-text-muted)",
    fontSize: "12px",
    fontWeight: 650,
    textTransform: "uppercase",
  },
  tree: {
    display: "grid",
    gap: "4px",
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  rootNode: {
    display: "grid",
    gap: "6px",
    padding: "8px 0 4px",
  },
  rootLabel: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
    color: "var(--color-text-muted)",
    fontSize: "12px",
    fontWeight: 650,
  },
  nodeButton: {
    width: "100%",
    border: 0,
    borderRadius: "6px",
    background: "transparent",
    color: "var(--color-text-primary)",
    cursor: "pointer",
    font: "inherit",
    padding: "7px 8px",
    textAlign: "left",
  },
  nodeStatic: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    color: "var(--color-text-secondary)",
    fontSize: "13px",
  },
  nodeContent: {
    display: "grid",
    gap: "2px",
  },
  nodeLabel: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    minWidth: 0,
    fontSize: "14px",
    fontWeight: 650,
  },
  nodeMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    color: "var(--color-text-muted)",
    fontSize: "12px",
    lineHeight: 1.35,
  },
  children: {
    display: "grid",
    gap: "3px",
    margin: "3px 0 0 12px",
    paddingLeft: "10px",
    borderLeft: "1px solid var(--color-border)",
    listStyle: "none",
  },
  project: {
    display: "grid",
    gap: "8px",
    paddingTop: "10px",
    borderTop: "1px solid var(--color-border)",
  },
  projectHeader: {
    display: "grid",
    gap: "3px",
  },
  selectedContext: {
    display: "grid",
    gap: "6px",
    marginTop: "16px",
    padding: "10px",
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    background: "#f6f8fa",
  },
} as const;
